#define HAS_ARGZ_H	0
#define HAS_WCTYPE_H	1
#define HAS_STRLCPY	1
#define HAS_ASPRINTF	1
#define HAS_LOCALES	1
#define HAS_PTY		1

#define HAS_MESSAGE_SLEEP_BUG	0
#define HAS_PROC		0
#define HAS_PROC_SELF_EXE	0
#define HAS_FOUR_BYTES_PTY	0
#define HAS_CONSOLE_HACK	0
#define HAS_FIND_USER_DIRECTORY	1
#define HAS_CREATE_PATH		1
#define HAS_LONG_PATHS		0
#define HAS_CW_INT_SETLOCALE	0
#define NEEDS_EXPLICIT_WINCON_H	0
#define NEEDS_WINDOWS_VER	0
